// Pure translation table for the admin UI — no server-only imports, so this is
// safe to import from client components (Sidebar, FlashBanner) as well as the
// server helper in admin-i18n.js.
export const DICT = {
  en: {
    // ── Sidebar / chrome ──
    logoTag: 'Admin',
    'nav.dashboard': 'Dashboard',
    'nav.group.content': 'Content',
    'nav.group.pages': 'Pages & Sections',
    'nav.group.inbox': 'Inbox',
    'nav.group.system': 'System',
    'nav.projects': 'Our Work',
    'nav.team': 'Team',
    'nav.clients': 'Clients',
    'nav.posts': 'Media Posts',
    'nav.pages': 'Pages',
    'nav.principles': 'Vision / Mission / Values',
    'nav.stats': 'Homepage Stats',
    'nav.sectors': 'Sectors',
    'nav.pillars': 'Services (TRACE)',
    'nav.offices': 'Offices',
    'nav.messages': 'Messages',
    'nav.jobs': 'Careers',
    'nav.applications': 'Applications',
    'nav.settings': 'Settings',
    signOut: 'Sign out',
    languageName: 'العربية', // label on the toggle → switches TO Arabic
    openMenu: 'Open navigation menu',
    closeMenu: 'Close navigation menu',

    // ── Common actions ──
    'action.new': 'New',
    'action.add': 'Add',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.deleting': 'Deleting…',
    'action.save': 'Save',
    'action.saving': 'Saving…',
    'action.cancel': 'Cancel',
    'action.back': 'Back',
    'action.view': 'View',

    // ── Flash / status ──
    'flash.saved': 'Changes saved successfully.',
    'flash.deleted': 'Deleted successfully.',
    'status.published': 'Published',
    'status.draft': 'Draft',
    'status.hidden': 'Hidden',
    'status.visible': 'Visible',
    'status.read': 'Read',
    'status.new': 'New',
    'status.reviewed': 'Reviewed',
    'status.active': 'Active',
    'status.closed': 'Closed',

    // ── Dashboard ──
    'dash.title': 'Dashboard',
    'dash.sub': 'Overview of your content and inbox.',
    'dash.unread': 'Unread messages',
    'dash.newApps': 'New applications',
    'dash.projects': 'Projects',
    'dash.team': 'Team members',
    'dash.clients': 'Clients',
    'dash.posts': 'Media posts',
    'dash.jobs': 'Active jobs',

    // ── List page titles ──
    'page.projects.title': 'Our Work',
    'page.team.title': 'Leadership',
    'page.clients.title': 'Clients',
    'page.posts.title': 'Media Posts',
    'page.pages.title': 'Pages',
    'page.principles.title': 'Vision / Mission / Values',
    'page.stats.title': 'Homepage Stats',
    'page.sectors.title': 'Sectors',
    'page.pillars.title': 'Services (TRACE Pillars)',
    'page.offices.title': 'Offices',
    'page.messages.title': 'Messages',
    'page.jobs.title': 'Careers',
    'page.applications.title': 'Job Applications',
    'page.settings.title': 'Settings',
    'page.settings.sub': 'Manage global site and account settings.',

    // ── "New" buttons ──
    'new.project': '+ New Project',
    'new.team': '+ New Member',
    'new.client': '+ New Client',
    'new.post': '+ New Post',
    'new.principle': '+ New Entry',
    'new.stat': '+ New Stat',
    'new.sector': '+ New Sector',
    'new.pillar': '+ New Pillar',
    'new.office': '+ New Office',
    'new.job': '+ New Job',

    // ── Table headers ──
    'th.title': 'Title',
    'th.client': 'Client',
    'th.year': 'Year',
    'th.status': 'Status',
    'th.name': 'Name',
    'th.position': 'Position',
    'th.website': 'Website',
    'th.author': 'Author',
    'th.page': 'Page',
    'th.heroTitle': 'Hero title',
    'th.type': 'Type',
    'th.value': 'Value',
    'th.label': 'Label',
    'th.letter': 'Letter',
    'th.city': 'City',
    'th.phone': 'Phone',
    'th.from': 'From',
    'th.subject': 'Subject',
    'th.received': 'Received',
    'th.department': 'Department',
    'th.applicant': 'Applicant',
    'th.applied': 'Applied',

    // ── Empty states ──
    'empty.projects': 'No projects yet. Create your first one.',
    'empty.team': 'No team members yet. Create your first one.',
    'empty.clients': 'No clients yet. Create your first one.',
    'empty.posts': 'No posts yet. Create your first one.',
    'empty.pages': 'No pages yet.',
    'empty.principles': 'No entries yet. Create your first one.',
    'empty.stats': 'No stats yet. Create your first one.',
    'empty.sectors': 'No sectors yet. Create your first one.',
    'empty.pillars': 'No pillars yet. Create your first one.',
    'empty.offices': 'No offices yet. Create your first one.',
    'empty.messages': 'No messages yet.',
    'empty.jobs': 'No jobs yet. Create your first one.',
    'empty.applications': 'No applications yet.',

    // ── Count units (shown after a number in list subtitles) ──
    'unit.projects': 'projects',
    'unit.team': 'members',
    'unit.clients': 'clients',
    'unit.posts': 'posts',
    'unit.pages': 'pages',
    'unit.principles': 'entries',
    'unit.stats': 'stats',
    'unit.sectors': 'sectors',
    'unit.pillars': 'pillars',
    'unit.offices': 'offices',
    'unit.messages': 'messages',
    'unit.jobs': 'jobs',
    'unit.applications': 'applications',

    // ── Detail / misc ──
    'detail.backToInbox': 'Back to inbox',
    'detail.from': 'From',
    'detail.email': 'Email',
    'detail.subject': 'Subject',
    'detail.received': 'Received',
    'detail.message': 'Message',
    'detail.markRead': 'Mark as read',
    'detail.markUnread': 'Mark as unread',
    'detail.position': 'Position',
    'detail.phone': 'Phone',
    'detail.applied': 'Applied',
    'detail.cv': 'CV',
    'detail.openCv': 'Open CV',
    'detail.markReviewed': 'Mark reviewed',
    'detail.markNew': 'Mark as new',
    'detail.newApplication': 'New application',
    'detail.reviewed': 'Reviewed',
    'detail.noSubject': '(no subject)',
    'detail.unknown': 'Unknown',

    // ── Dashboard (redesign) ──
    'account.name': 'Administrator',
    'account.role': 'ProEx Admin',
    'dash.greeting.morning': 'Good morning',
    'dash.greeting.afternoon': 'Good afternoon',
    'dash.greeting.evening': 'Good evening',
    'dash.greetSub': "Here's what's happening across your site today",
    'dash.needsAttention': 'Needs attention',
    'dash.overview': 'Overview',
    'dash.recentActivity': 'Recent activity',
    'dash.awaitingReply': 'Awaiting your reply',
    'dash.inboxZero': 'Inbox zero — all caught up',
    'dash.needsReview': 'Needs review',
    'dash.allReviewed': 'All reviewed',
    'dash.ctx.portfolio': 'In your portfolio',
    'dash.ctx.team': 'People on the team',
    'dash.ctx.clients': 'Client organizations',
    'dash.ctx.jobs': 'Currently open',
    'kpi.postsSplit': '{pub} published · {draft} draft',
    'kpi.postsEmpty': 'No posts yet',
    'dash.action.newPost': 'New post',
    'dash.action.newProject': 'New project',
    'dash.action.newTeam': 'Add team member',
    'dash.action.newClient': 'Add client',
    'dash.translationHealth': 'Translation health',
    'dash.missingArabic': 'missing Arabic',
    'dash.fullyBilingual': 'Fully bilingual',
    'dash.publishing': 'Publishing status',
    'dash.published': 'Published',
    'dash.draft': 'Draft',
    'dash.postsTotal': 'posts',
    'dash.noActivity': 'No recent activity yet',
    'dash.noActivitySub': 'Content changes will appear here',
    'act.message': 'New message from',
    'act.applied': 'applied for',
    'act.post': 'Post:',
    'act.project': 'Project added:',
    'time.now': 'just now',
    'time.min': 'min',
    'time.hr': 'h',
    'time.day': 'd',
    'time.ago': 'ago',

    // ── Generic ──
    confirmDelete: 'Delete this permanently? This cannot be undone.',
    requiredLang: 'Missing Arabic',
  },
  ar: {
    logoTag: 'لوحة الإدارة',
    'nav.dashboard': 'لوحة التحكم',
    'nav.group.content': 'المحتوى',
    'nav.group.pages': 'الصفحات والأقسام',
    'nav.group.inbox': 'صندوق الوارد',
    'nav.group.system': 'النظام',
    'nav.projects': 'أعمالنا',
    'nav.team': 'الفريق',
    'nav.clients': 'العملاء',
    'nav.posts': 'المنشورات الإعلامية',
    'nav.pages': 'الصفحات',
    'nav.principles': 'الرؤية / الرسالة / القيم',
    'nav.stats': 'إحصائيات الصفحة الرئيسية',
    'nav.sectors': 'القطاعات',
    'nav.pillars': 'الخدمات (TRACE)',
    'nav.offices': 'المكاتب',
    'nav.messages': 'الرسائل',
    'nav.jobs': 'الوظائف',
    'nav.applications': 'طلبات التوظيف',
    'nav.settings': 'الإعدادات',
    signOut: 'تسجيل الخروج',
    languageName: 'English', // switches back to English
    openMenu: 'فتح قائمة التنقل',
    closeMenu: 'إغلاق قائمة التنقل',

    'action.new': 'إضافة',
    'action.add': 'إضافة',
    'action.edit': 'تعديل',
    'action.delete': 'حذف',
    'action.deleting': 'جارٍ الحذف…',
    'action.save': 'حفظ',
    'action.saving': 'جارٍ الحفظ…',
    'action.cancel': 'إلغاء',
    'action.back': 'رجوع',
    'action.view': 'عرض',

    'flash.saved': 'تم حفظ التغييرات بنجاح.',
    'flash.deleted': 'تم الحذف بنجاح.',
    'status.published': 'منشور',
    'status.draft': 'مسودة',
    'status.hidden': 'مخفي',
    'status.visible': 'ظاهر',
    'status.read': 'مقروء',
    'status.new': 'جديد',
    'status.reviewed': 'تمت المراجعة',
    'status.active': 'نشط',
    'status.closed': 'مغلق',

    'dash.title': 'لوحة التحكم',
    'dash.sub': 'نظرة عامة على المحتوى وصندوق الوارد.',
    'dash.unread': 'رسائل غير مقروءة',
    'dash.newApps': 'طلبات توظيف جديدة',
    'dash.projects': 'المشاريع',
    'dash.team': 'أعضاء الفريق',
    'dash.clients': 'العملاء',
    'dash.posts': 'المنشورات الإعلامية',
    'dash.jobs': 'الوظائف النشطة',

    'page.projects.title': 'أعمالنا',
    'page.team.title': 'القيادة',
    'page.clients.title': 'العملاء',
    'page.posts.title': 'المنشورات الإعلامية',
    'page.pages.title': 'الصفحات',
    'page.principles.title': 'الرؤية / الرسالة / القيم',
    'page.stats.title': 'إحصائيات الصفحة الرئيسية',
    'page.sectors.title': 'القطاعات',
    'page.pillars.title': 'الخدمات (ركائز TRACE)',
    'page.offices.title': 'المكاتب',
    'page.messages.title': 'الرسائل',
    'page.jobs.title': 'الوظائف',
    'page.applications.title': 'طلبات التوظيف',
    'page.settings.title': 'الإعدادات',
    'page.settings.sub': 'إدارة إعدادات الموقع والحساب العامة.',

    'new.project': '+ مشروع جديد',
    'new.team': '+ عضو جديد',
    'new.client': '+ عميل جديد',
    'new.post': '+ منشور جديد',
    'new.principle': '+ إدخال جديد',
    'new.stat': '+ إحصائية جديدة',
    'new.sector': '+ قطاع جديد',
    'new.pillar': '+ ركيزة جديدة',
    'new.office': '+ مكتب جديد',
    'new.job': '+ وظيفة جديدة',

    'th.title': 'العنوان',
    'th.client': 'العميل',
    'th.year': 'السنة',
    'th.status': 'الحالة',
    'th.name': 'الاسم',
    'th.position': 'المنصب',
    'th.website': 'الموقع الإلكتروني',
    'th.author': 'الكاتب',
    'th.page': 'الصفحة',
    'th.heroTitle': 'عنوان الواجهة',
    'th.type': 'النوع',
    'th.value': 'القيمة',
    'th.label': 'التسمية',
    'th.letter': 'الحرف',
    'th.city': 'المدينة',
    'th.phone': 'الهاتف',
    'th.from': 'من',
    'th.subject': 'الموضوع',
    'th.received': 'تاريخ الاستلام',
    'th.department': 'القسم',
    'th.applicant': 'المتقدم',
    'th.applied': 'تاريخ التقديم',

    'empty.projects': 'لا توجد مشاريع بعد. أضِف أول مشروع.',
    'empty.team': 'لا يوجد أعضاء فريق بعد. أضِف أول عضو.',
    'empty.clients': 'لا يوجد عملاء بعد. أضِف أول عميل.',
    'empty.posts': 'لا توجد منشورات بعد. أضِف أول منشور.',
    'empty.pages': 'لا توجد صفحات بعد.',
    'empty.principles': 'لا توجد إدخالات بعد. أضِف أول إدخال.',
    'empty.stats': 'لا توجد إحصائيات بعد. أضِف أول إحصائية.',
    'empty.sectors': 'لا توجد قطاعات بعد. أضِف أول قطاع.',
    'empty.pillars': 'لا توجد ركائز بعد. أضِف أول ركيزة.',
    'empty.offices': 'لا توجد مكاتب بعد. أضِف أول مكتب.',
    'empty.messages': 'لا توجد رسائل بعد.',
    'empty.jobs': 'لا توجد وظائف بعد. أضِف أول وظيفة.',
    'empty.applications': 'لا توجد طلبات توظيف بعد.',

    'unit.projects': 'مشاريع',
    'unit.team': 'أعضاء',
    'unit.clients': 'عملاء',
    'unit.posts': 'منشورات',
    'unit.pages': 'صفحات',
    'unit.principles': 'إدخالات',
    'unit.stats': 'إحصائيات',
    'unit.sectors': 'قطاعات',
    'unit.pillars': 'ركائز',
    'unit.offices': 'مكاتب',
    'unit.messages': 'رسائل',
    'unit.jobs': 'وظائف',
    'unit.applications': 'طلبات',

    'detail.backToInbox': 'العودة إلى صندوق الوارد',
    'detail.from': 'من',
    'detail.email': 'البريد الإلكتروني',
    'detail.subject': 'الموضوع',
    'detail.received': 'تاريخ الاستلام',
    'detail.message': 'الرسالة',
    'detail.markRead': 'تحديد كمقروء',
    'detail.markUnread': 'تحديد كغير مقروء',
    'detail.position': 'المنصب',
    'detail.phone': 'الهاتف',
    'detail.applied': 'تاريخ التقديم',
    'detail.cv': 'السيرة الذاتية',
    'detail.openCv': 'فتح السيرة الذاتية',
    'detail.markReviewed': 'تحديد كمُراجَع',
    'detail.markNew': 'تحديد كجديد',
    'detail.newApplication': 'طلب توظيف جديد',
    'detail.reviewed': 'تمت المراجعة',
    'detail.noSubject': '(بدون موضوع)',
    'detail.unknown': 'غير معروف',

    // ── Dashboard (redesign) ──
    'account.name': 'المشرف',
    'account.role': 'مسؤول برو إكس',
    'dash.greeting.morning': 'صباح الخير',
    'dash.greeting.afternoon': 'مساء الخير',
    'dash.greeting.evening': 'مساء الخير',
    'dash.greetSub': 'إليك ما يجري في موقعك اليوم',
    'dash.needsAttention': 'يتطلب انتباهك',
    'dash.overview': 'نظرة عامة',
    'dash.recentActivity': 'النشاط الأخير',
    'dash.awaitingReply': 'بانتظار ردّك',
    'dash.inboxZero': 'لا رسائل غير مقروءة',
    'dash.needsReview': 'بحاجة إلى مراجعة',
    'dash.allReviewed': 'تمت مراجعة الكل',
    'dash.ctx.portfolio': 'ضمن أعمالك',
    'dash.ctx.team': 'أعضاء الفريق',
    'dash.ctx.clients': 'جهات العملاء',
    'dash.ctx.jobs': 'مفتوحة حالياً',
    'kpi.postsSplit': '{pub} منشور · {draft} مسودة',
    'kpi.postsEmpty': 'لا منشورات بعد',
    'dash.action.newPost': 'منشور جديد',
    'dash.action.newProject': 'مشروع جديد',
    'dash.action.newTeam': 'إضافة عضو',
    'dash.action.newClient': 'إضافة عميل',
    'dash.translationHealth': 'اكتمال الترجمة',
    'dash.missingArabic': 'بدون ترجمة عربية',
    'dash.fullyBilingual': 'مكتمل الترجمة',
    'dash.publishing': 'حالة النشر',
    'dash.published': 'منشور',
    'dash.draft': 'مسودة',
    'dash.postsTotal': 'منشور',
    'dash.noActivity': 'لا يوجد نشاط بعد',
    'dash.noActivitySub': 'ستظهر تغييرات المحتوى هنا',
    'act.message': 'رسالة جديدة من',
    'act.applied': 'تقدّم لوظيفة',
    'act.post': 'منشور:',
    'act.project': 'مشروع جديد:',
    'time.now': 'الآن',
    'time.min': 'دقيقة',
    'time.hr': 'ساعة',
    'time.day': 'يوم',
    'time.ago': 'منذ',

    confirmDelete: 'حذف هذا نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.',
    requiredLang: 'الترجمة العربية ناقصة',
  },
};

// Pure key resolver: falls back to English, then to the key itself.
export function translate(locale, key) {
  const table = DICT[locale] || DICT.en;
  return table[key] ?? DICT.en[key] ?? key;
}

// Convenience factory for a bound t(key).
export function makeT(locale) {
  return (key) => translate(locale, key);
}
